# Generated by Django 6.1 on 2026-09-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
