# Generated by Django 6.1 on 2026-09-08 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Car', 'car'), ('Bus', 'bus'), ('Motorbike', 'motorbike'), ('Bike', 'bike')], default='Car')),
                ('RegNo', models.CharField(max_length=15, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
