# Generated by Django 6.1 on 2026-09-09 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motors', '0001_initial'),
        ('slots', '0002_alter_slot_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_type', models.CharField(choices=[('Car', 'car'), ('Bus', 'bus'), ('Motorbike', 'motorbike'), ('Bike', 'bike')], help_text='The vehicle type this price applies to.', unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate charge for this vehicle type.', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('total_charges', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('reserved', 'Reserved'), ('Cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='motors.motor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='slots.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
